#!/bin/bash
set -EeufC -o pipefail -o emacs
shopt -s checkhash extglob lastpipe gnu_errfmt mailwarn shift_verbose
shopt -s dotglob nullglob    # These don't actually do anything now because of the 'set -f', but if I want to use filename globbing in a particular script with 'set +f', then these seem like good ideas.
